/****************************************************************************
 *	Copyright 2012 HES-SO HEIG-VD
 *	Copyright 2011 HES-SO Valais Wallis
 *	Copyright 2007-2010 Mentor Graphics Corporation
 *	Copyright 2007-2010 Cadence Design Systems, Inc.
 *	Copyright 2010 Synopsys, Inc.
 *	All Rights Reserved Worldwide
 *
 *	Licensed under the Apache License, Version 2.0 (the "License");
 *	you may not use this file except in compliance with the License.
 *	You may obtain a copy of the License at
 *
 *		http://www.apache.org/licenses/LICENSE-2.0
 *
 *	Unless required by applicable law or agreed to in writing, software
 *	distributed under the License is distributed on an "AS IS" BASIS,
 *	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *	See the License for the specific language governing permissions and
 *	limitations under the License.
 ****************************************************************************
 * This file has been generated by UVE version $@uve_version@$
 * Date of generation: $@date@$
 *
 * Project : $@projectname@$
 * File : $@filename@$
 * Version : 1.0
 ****************************************************************************
 * Description :
 * Every component is characterized by its interface, regardless of its
 * internal implementation.
 ****************************************************************************/

`ifndef $@FILENAME@$
`define $@FILENAME@$

interface $@ClassName@$;

        // Checks and coverage control bits
        bit has_checks = 1;
        bit has_coverage = 1;

        // Interface signals
        $@ interface_signals

        // Checks
/*---------------------------------------------------------------------------
 * @TODO : Implement checks
 * see UVM User Guide - 4.12 Implementing Checks and Coverage
 *--------------------------------------------------------------------------*/

        // Assertions
/*---------------------------------------------------------------------------
 * @TODO : Implement coverage
 * see UVM User Guide - 4.12 Implementing Checks and Coverage
 *--------------------------------------------------------------------------*/

endinterface : $@ClassName@$

`endif /* $@FILENAME@$ */

