/****************************************************************************
 *	Copyright 2012 HES-SO HEIG-VD
 *	Copyright 2011 HES-SO Valais Wallis
 *	Copyright 2007-2010 Mentor Graphics Corporation
 *	Copyright 2007-2010 Cadence Design Systems, Inc.
 *	Copyright 2010 Synopsys, Inc.
 *	All Rights Reserved Worldwide
 *
 *	Licensed under the Apache License, Version 2.0 (the "License");
 *	you may not use this file except in compliance with the License.
 *	You may obtain a copy of the License at
 *
 *		http://www.apache.org/licenses/LICENSE-2.0
 *
 *	Unless required by applicable law or agreed to in writing, software
 *	distributed under the License is distributed on an "AS IS" BASIS,
 *	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *	See the License for the specific language governing permissions and
 *	limitations under the License.
 ****************************************************************************
 * This file has been generated by UVE version $@uve_version@$
 * Date of generation: $@date@$
 *
 * Project : $@projectname@$
 * File : $@filename@$
 * Version : 1.0
 ****************************************************************************
 * Description :
 * A sequencer is an advanced stimulus generator that controls the items
 * that are provided to the driver for execution.
 ****************************************************************************/

`ifndef $@FILENAME@$
`define $@FILENAME@$

`include "uvm_macros.svh"

class $@ClassName@$ extends uvm_sequencer #($@vip_transfer@$);

        // TLM port to peek the transfer from the slave monitor
       uvm_blocking_peek_port#($@vip_transfer@$) seq_item_port;

        // Provide implementations of virtual methods such as get_type_name and create
        `uvm_sequencer_utils($@ClassName@$)

        // Constructor
        function new(string name = "agent sequencer", uvm_component parent);

                super.new(name, parent);
               
                // Create port
                seq_item_port = new("seq_item_port", this);

        endfunction : new

endclass : $@ClassName@$

`endif /* $@FILENAME@$ */
